### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by kylewlacy** [DylanPiercey/content-check#1]
Hi, I really like the looks of Rill and the set of libraries that you've built for it! I'm interested in potentially using Rill for a project, but I noticed that this library as well as [header-field](https://github.com/DylanPiercey/header-field) don't have `LICENSE` files nor a `"license"` field in their respective `package.json` files.

Could you possibly add a license to both libraries so I can use them? I'd personally like to see MIT (just like what Rill itself uses), but I'm not picky!

**Comment by DylanPiercey** [comment]
Hey @kylewlacy, thanks for your interest in the project. I'd be totally okay with adding the MIT license to any existing rill module. I'll take a look at this when I get some time hopefully tonight or tomorrow. If you'd like it'd be a great chance for a couple of PR's as well. :)

**Comment by DylanPiercey** [comment]
Added licenses to both projects. If you notice any others that are missing just let me know.
